version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_USER: alx_user
      MYSQL_PASSWORD: !UGO2811!
      MYSQL_DB: alx_prodev
      MYSQL_ROOT_PASSWORD: !UGO2811!
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: alx_prodev
      DB_USER: alx_user
      DB_PASSWORD: !UGO2811!
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
