pipeline {
    agent {
        docker {
            image 'python:3.10'   // Run inside a Python container
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Chuksugo/alx-backend-python.git',
                    branch: 'main',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                // Run pytest and generate JUnit XML report
                sh 'pytest --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                // Publish the test results to Jenkins
                junit 'report.xml'
            }
        }
    }
}
