pipeline {
    agent {
        docker {
            image 'python:3.10'   // Python image with pip already installed
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Chuksugo/alx-backend-python.git',
                    branch: 'main',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings -q'
            }
        }
    }
}
